### ISSUE TITLE
💄 [add or update the UI] 주식 상세 대시보드

### ISSUE THREAD

**Issue by YJKBigBo** [fianlProjectTeam2/client#10]
# 🤖 변경 및 기능 개요
주식 목록에서 선택된 주식의 대시보드

## ✅ Todo
- [ ] 구현 내용 1. 대시보드 디자인
- [ ] 구현 내용 2. 주식목록에서의 주식 대시보드 페이지로의 값 전달
- [ ] 구현 내용 3. 대시보드의 차트 다양화

### 📚 Remarks
api 주소 변경 혹은 데이터 타입의 변경이 있을 수 있음
