### ISSUE TITLE
🔨 [feature] 주식목록 api 적용

### ISSUE THREAD

**Issue by YJKBigBo** [fianlProjectTeam2/client#12]
# 🤖 기능 개요
주식목록을 공공 api를 사용해 데이터를 가져와 제공

## ✅ Todo
- [ ] 구현 내용 1. 공공데이터 가져오기
- [ ] 구현 내용 2. 데이터 파싱
- [ ] 구현 내용 3. UI 구현
