### ISSUE TITLE
🔨 [feature] 메인화면 차트

### ISSUE THREAD

**Issue by YJKBigBo** [fianlProjectTeam2/client#2]
# 🤖 기능 개요
메인화면에 노출되는 주식별 차트

## ✅ Todo
- [ ] 구현 내용 1. 주식 api를 사용하여 데이터를 가져온다.
- [ ] 구현 내용 2. 데이터를 파싱한다.
- [ ] 구현 내용 3. 파싱한 데이터를 사용하여 주식 차트를 작성한다.

### 📚 Remarks
추후 API 주소 바뀔 가능성있으니 체크 해야함
