### ISSUE TITLE
🔨 [feature] 주식 상세차트

### ISSUE THREAD

**Issue by YJKBigBo** [fianlProjectTeam2/client#4]
# 🤖 기능 개요
메인화면으로 부터 이동한 해당 주식의 상세차트를 그리도록 하는 페이지로 메인화면 보다 더 상세한 차트를 그린다.

## ✅ Todo
- [x] 구현 내용 1. 상세페이지의 디자인
- [x] 구현 내용 2. 상세페이지의 api 데이터 파싱
- [x] 구현 내용 3. 파싱 데이터 charJS사용

### 📚 Remarks
api를 변동 사항이 있을 수 있으니 참고 해야함

**Comment by YJKBigBo** [comment]
ChartJS에서 ApexCharts로 변경
